/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class deck_Clib_Random_JNI */

#ifndef _Included_deck_Clib_Random_JNI
#define _Included_deck_Clib_Random_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     deck_Clib_Random_JNI
 * Method:    clib_rand
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_deck_Clib_1Random_1JNI_clib_1rand
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
